# Add labels when specific files are changed
translations:
  - any: ['i18n/**/*']

documentation:
  - any: ['docs/**/*.md', 'docs/**/*.mdx']

dependencies:
  - 'package.json'
  - 'package-lock-json'

docusaurus-config:
  - 'docusaurus.config.js'